import { useState } from "react";
import Head from "next/head";

import { TransactionsProvider } from "@/hooks/useTransactions";

import Dashboard from "@/components/Dashboard/Dashboard";
import Header from "@/components/Header/Header";
import NewTransactionModal from "@/components/Modals/NewTransactionModal";


export default function Home() {
  const [isNewTransactionModalOpen, setIsNewTransactionModalOpen] =
    useState(false);

  const openNewTransactionModal = () => setIsNewTransactionModalOpen(true);
  const closeNewTransactionModal = () => setIsNewTransactionModalOpen(false);

  return (
    <>
      <Head>
        <title>Ticto Teste</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TransactionsProvider>
          <Header openNewTransactionModal={openNewTransactionModal} />

          <Dashboard />

          <NewTransactionModal
            closeNewTransactionModal={closeNewTransactionModal}
            isNewTransactionModalOpen={isNewTransactionModalOpen}
          />
        </TransactionsProvider>
      </main>
    </>
  );
}
